### ISSUE TITLE
eSD boot and top/save address

### ISSUE THREAD

**Issue by ljkeller** [renesas-rz/rzg2_flash_writer#1]
Hello!

This is a great tool you have created. **I was wondering if it would be possible for you to elaborate more on the top / save address in the documentation somewhere?** I want to understand these addresses better, and see how they relate to my use case.

I have a few RZBoards and RZ/V2L EVKs + other renesas products.

My **RZ/V2Ls have old silicon known as the discrete version** https://community.renesas.com/rz/f/rz-forum/30275/rz-v2l-scif-download-mode-issue . This has lead to my bootloader files being different than what is currently represented in Renesas RZ/V2L documentation. **I believe this also means I'll have different top and save addresses for my bootloader files**

I'd also like to know how eSD boot works: storing bootloader files and kernel together on a uSD card with a special dipswitch configuration: 
![image](https://github.com/renesas-rz/rzg2_flash_writer/assets/44109284/1e24a65f-f804-4b71-963c-22333e9a287f)

**Does this mean that the top/save addresses for the bootloader files in uSD are stored in ROM as default values and selected by the dipswitch configuration?**

I'm excited to hear back from you, I have several problems to solve!

**Comment by seebe** [comment]
The addresses you save to will be the same (Discrete power board vs PMIC power board). The reason that the boot loaders are different is that the DDR chip are different between the two boards. But, the programming addresses are the same.

As for eSD boot, or rather booting directly from an SD card (not SPI Flash, no eMMC flash), there are some instructions here for the RZ/G2L, which is the same as the RZ/V2L (they use the same base board).
https://renesas.info/wiki/RZ-G/RZ-G2L_SMARC#SD_card_boot

**Comment by ljkeller** [comment]
Thank you!

This seems to imply that for eSD boot, the top address and save address for FIP/BL2 are stored somewhere and loaded by the eSD boot dip switch configuration? Just trying to understand that last detail on how the board knows where to look for FIP/BL2 when the bootloaders are stored in SD card. 

**It seems like this dip switch configuration logic is essentially: look for the u-boot configuration at sector 1 (boot parameters, 512 bytes).**

![image](https://github.com/renesas-rz/rzg2_flash_writer/assets/44109284/ad4dc5e9-2728-4c8b-8c0a-b11524ed02a4)

Thanks again for the quick response!

**Comment by seebe** [comment]
After RESET, the SoC first reads out the boot parameter table from Sector 1 into internal RAM in the SoC. That is fixed...cannot be changed. But, that boot parameter table is then read and has the location and size of BL2. But, it looks like the location of BL2 is also fixed at Sector 8.

What you can change is the location and size of the FIP. You can change that in code.

It seems like you have the right idea.

**Comment by ljkeller** [comment]
Thanks for clearing that up.

Maybe this outdated block of VLP 3.0.2 and 3.0.4 RZV2L getting started guide could be updated to include this information:
![image](https://github.com/renesas-rz/rzg2_flash_writer/assets/44109284/7f172b95-21be-4d7f-9d98-5d7a78507461)


Those questions were all I need for now- thanks again!
