### ISSUE TITLE
RZ/Five compatibility

### ISSUE THREAD

**Issue by yogo1212** [renesas-rz/rzg2_flash_writer#2]
https://renesas.info/wiki/RZ-Five/RZ-Five-BSP_Porting mentions this repo for use with the RZ/Five, however, it is not mentioned in the README.

How is this used with the RZ/Five Group?

**Comment by seebe** [comment]
There is a separate branch for RZ/Five. It is listed on the wiki page of this repo.

https://github.com/renesas-rz/rzg2_flash_writer/wiki

**Comment by yogo1212** [comment]
Alright - thanks!
